# Generated by Django 3.2.18 on 2023-03-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comptes_Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
    ]
