# Generated by Django 3.2.13 on 2023-04-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comptes_Utilisateurs', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='photoProfil'),
        ),
    ]
