# Generated by Django 3.2.18 on 2023-03-30 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=75, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=75, verbose_name='Prenom')),
                ('numeroTelephone', models.CharField(max_length=75, verbose_name='Numero Téléphone')),
                ('dateCreation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('is_client', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=75)),
                ('message', models.TextField()),
                ('dateEnvoi', models.DateTimeField(auto_now=True)),
                ('idClient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clients.client')),
            ],
        ),
    ]
