# Generated by Django 4.2 on 2023-04-25 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Services_Offres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleCategorie', models.CharField(max_length=80, verbose_name='Libelle Catégorie')),
            ],
            options={
                'verbose_name': 'Categorie Produit',
                'verbose_name_plural': 'Categorie Produits',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('numeroCom', models.CharField(editable=False, max_length=80, primary_key=True, serialize=False, verbose_name='Numero de Commande Généré automatiquement')),
                ('montantCom', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Facture')),
                ('dateCreationCom', models.DateTimeField(verbose_name='Date de création')),
                ('etatCommande', models.BooleanField(default=False, verbose_name='Etat de la commande')),
                ('nombreProduit', models.IntegerField(verbose_name='Nombre de produit total Commander')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Email Cleint')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commande',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('numeroRes', models.CharField(editable=False, max_length=80, primary_key=True, serialize=False, verbose_name='Numéro de réservation généné automatiquement')),
                ('dateReservation', models.DateField(verbose_name='Date de réservation')),
                ('heureReservation', models.TimeField(verbose_name='Heure de réservation')),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Services_Offres.service', verbose_name='Service')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellePro', models.CharField(max_length=80, verbose_name='Libelle Produit')),
                ('prixPro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Produit')),
                ('QteProduit', models.IntegerField(verbose_name='Quantité de produit')),
                ('descriptionPro', models.TextField(max_length=1500, verbose_name='Description')),
                ('photoProduit', models.ImageField(blank=True, default='default.jpg', upload_to='photoProduit')),
                ('dateCreationPro', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='produits', to='Clients.categorieprod')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=75)),
                ('message', models.TextField()),
                ('dateEnvoi', models.DateTimeField(auto_now=True)),
                ('reponse', models.TextField(default="Vous n'avez pas encore de réponse à ce message")),
                ('repondu', models.BooleanField(default=False)),
                ('idUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mail Client')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('numeroFact', models.CharField(editable=False, max_length=80, primary_key=True, serialize=False, verbose_name='Numero de Facture Généré automatiquement')),
                ('totalFact', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Facture')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('etatFact', models.BooleanField(default=False, verbose_name='Etat Facture')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Email Cleint')),
                ('numeroCom', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Clients.commande', verbose_name='Numéro de commande')),
                ('numeroResv', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clients.reservation', verbose_name='Numéro de réservation')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='CommanderProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Email Cleint')),
                ('numeroCom', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Clients.commande', verbose_name='Numéro de commande')),
            ],
            options={
                'verbose_name': 'CommanderProduit',
                'verbose_name_plural': 'CommanderProduit',
            },
        ),
    ]
