# Generated by Django 3.2.18 on 2023-04-04 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Services_Offres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('numeroFact', models.CharField(editable=False, max_length=80, primary_key=True, serialize=False, verbose_name='Numero de Facture Généré automatiquement')),
                ('totalFact', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Facture')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('etatFact', models.BooleanField(default=False, verbose_name='Etat Facture')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=75)),
                ('message', models.TextField()),
                ('dateEnvoi', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('numeroRes', models.CharField(editable=False, max_length=80, primary_key=True, serialize=False, verbose_name='Numéro de réservation généné automatiquement')),
                ('dateReservation', models.DateField(verbose_name='Date de réservation')),
                ('heureReservation', models.TimeField(verbose_name='Heure de réservation')),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services_Offres.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
    ]
