# Generated by Django 3.2.18 on 2023-03-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='numeroRes',
            field=models.CharField(editable=False, max_length=80, primary_key=True, serialize=False, verbose_name='Numéro de réservation généné automatiquement'),
        ),
    ]
