# Generated by Django 3.2.13 on 2023-04-09 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='message',
            name='idUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mail Client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Email Cleint'),
        ),
        migrations.AddField(
            model_name='facture',
            name='numeroCom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Clients.commande', verbose_name='Numéro de commande'),
        ),
        migrations.AddField(
            model_name='facture',
            name='numeroResv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clients.reservation', verbose_name='Numéro de réservation'),
        ),
        migrations.AddField(
            model_name='composer',
            name='idCategorie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Clients.commande', verbose_name='ID Catégorie'),
        ),
        migrations.AddField(
            model_name='composer',
            name='idProduit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Clients.produit', verbose_name='ID Produit'),
        ),
        migrations.AddField(
            model_name='commanderproduit',
            name='idUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Email Cleint'),
        ),
        migrations.AddField(
            model_name='commanderproduit',
            name='numeroCom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Clients.commande', verbose_name='Numéro de commande'),
        ),
        migrations.AddField(
            model_name='commande',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Email Cleint'),
        ),
    ]
