# Generated by Django 3.2.18 on 2023-04-04 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='message',
            name='idUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mail Client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='idUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Email Cleint'),
        ),
        migrations.AddField(
            model_name='facture',
            name='numeroResv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clients.reservation', verbose_name='Numéro de réservation'),
        ),
    ]
