# Generated by Django 3.2.13 on 2023-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reponse',
            field=models.TextField(default="Vous n'avez pas encore de message"),
        ),
    ]
