# Generated by Django 4.2 on 2023-04-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_alter_produit_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='photoProduit',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
