# Generated by Django 3.2.18 on 2023-03-30 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clients', '0002_client_util'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='idClient',
        ),
        migrations.AddField(
            model_name='message',
            name='idUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
