# Generated by Django 3.2.13 on 2023-04-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='repondu',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
